# Generated by Django 5.1.3 on 2024-11-28 15:38

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_resetpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetP',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(editable=False, max_length=50, unique=True)),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('validate', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='ResetPassword',
        ),
    ]
