# Generated by Django 5.1.3 on 2024-11-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0003_resetp_delete_resetpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetP',
            new_name='ResetPassword',
        ),
        migrations.AlterModelManagers(
            name='resetpassword',
            managers=[
            ],
        ),
    ]
