# Generated by Django 5.1.3 on 2024-11-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0004_rename_resetp_resetpassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpassword',
            old_name='user',
            new_name='user_id',
        ),
    ]
